### ISSUE TITLE
Code is returning 403 - Must provide unique User-Agent in HTTP header 

### ISSUE THREAD

**Issue by jacobjordan94** [welps/giantbombing-api#1]
API access now requires that a unique User-Agent be sent in the request.
See here: [http://www.giantbomb.com/forums/api-developers-3017/q-getting-403-forbidden-when-requesting-images-1797588/#5](http://www.giantbomb.com/forums/api-developers-3017/q-getting-403-forbidden-when-requesting-images-1797588/#5)

Should be a pretty simple fix, this is really easy to do with [request.](https://www.npmjs.com/package/request#custom-http-headers) 
### Maybe something like this would be a good fix?

**Make user specify their user-agent in config object:**  

``` javascript
const GiantBombAPI = require('giantbombing-api');
const config = {
    apiKey: 'Your GiantBomb API code here'
    userAgent: 'Unique User-Agent goes here'
};
const giantBombAPI = new GiantBombAPI(config);
```

**Add userAgent as property of instance**

``` javascript
var GiantBombAPI = function(config){
    verifyConfig(config);
    createSingleNamedServices();
    createPluralNamedServices();

    this.apiKey = config.apiKey;
    this.userAgent = config.userAgent    
};
```

**And then when making the request :** 

``` javascript
var options = {
    url: (baseURL + resourcePath + '?api_key=' + this.apiKey + '&format=json&' + optionsQuery),
    headers: {
        'User-Agent': this.userAgent
    }
}
request(options, requestCallback);
```

**Comment by welps** [comment]
Thanks for filing this. I'm really sorry I missed it!
